name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies and Build Client
        run: |
          cd client
          npm install firebase
          npm install
          npx vite build --emptyOutDir

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAT_CHAT_B7187 }}'
          channelId: live
          projectId: gat-chat-b7187
